# Generated by Django 5.2.8 on 2025-11-13 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0003_alter_appointment_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='full_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
