# Generated by Django 5.2.8 on 2025-11-13 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0004_patientprofile_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='full_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
